# Generated by Django 2.0.6 on 2018-08-11 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0002_auto_20180811_1507'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flightplan',
            options={'get_latest_by': ['airline', 'number']},
        ),
    ]
