# Generated by Django 2.0.6 on 2018-08-11 15:25

from django.db import migrations

from collections import defaultdict

import datetime


def create(apps, schema_editor):
  Airport = apps.get_model('flights', 'Airport')
  Airline = apps.get_model('flights', 'Airline')
  FlightPlan = apps.get_model('flights', 'FlightPlan')

  last_flight_numbers = defaultdict(int)

  flight_plans = []

  for i in range(50000):
    departure_airport = Airport.objects.order_by('?').first()
    airline = Airline.objects.order_by("?").first()
    plan = FlightPlan(
      airline=airline,
      number=last_flight_numbers[airline.code],
      departure_airport=departure_airport,
      duration=datetime.timedelta(days=0, hours=0),
      arrival_airport=Airport.objects.order_by('?').exclude(code=departure_airport.code).first(),
    )

    last_flight_numbers[airline.code] += 1

    flight_plans.append(plan)

    if i % 1000 == 0:
      print("... %d done" % i)

  FlightPlan.objects.bulk_create(flight_plans)


class Migration(migrations.Migration):
  dependencies = [
    ('flights', '0004_auto_20180811_1406'),
  ]

  operations = [
    migrations.RunPython(create)
  ]
